<?php

namespace App\Listeners;

use App\Enums\GoodsIssueTypeEnum;
use App\Events\SaleCreated;
use App\Services\GoodsIssueService;

class CreateGoodsIssue
{
    /**
     * Handle the event.
     */
    public function handle(SaleCreated $event): void
    {
        $goodsIssueService = app(GoodsIssueService::class);
        $goodsIssueService->store([
            'company_id' => $event->companyId,
            'sale_id' => $event->saleId,
            'user_id' => $event->userId,
            'customer_id' => $event->customerId,
            'issue_date' => $event->saleDate,
            'sku' => $event->sku,
            'name' => $event->name,
            'quantity' => $event->quantity,
            'product_id' => $event->productId,
            'type' => GoodsIssueTypeEnum::SALE,
            'notes' => 'Generated by the System.',
        ]);
    }
}
